// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

package draft

import (
	"html"
	"regexp"
	"strings"
)

// QuoteWrapperClass is the CSS class name used by Lark's mail composer
// for reply/forward quote blocks. Both +reply and +forward wrap the
// quoted original message in a <div> with this class.
// Exported so that mail_quote.go (the generator) and projection.go
// (the detector) share a single source of truth.
const QuoteWrapperClass = "history-quote-wrapper"

// quoteWrapperRe matches an actual <div> element whose class attribute
// contains QuoteWrapperClass. This avoids false positives when the
// string appears as plain text, inside <pre> blocks, or in
// HTML-escaped content.
//
// Matches:
//   - <div class="history-quote-wrapper">           (reply)
//   - <div id="..." class="history-quote-wrapper">  (forward)
var quoteWrapperRe = regexp.MustCompile(`<div\s[^>]*class="[^"]*` + QuoteWrapperClass + `[^"]*"`)

var cidRefRegexp = regexp.MustCompile(`(?i)cid:([^"' >]+)`)

// SignatureWrapperClass is the CSS class for the mail signature container.
const SignatureWrapperClass = "lark-mail-signature"

var signatureWrapperRe = regexp.MustCompile(
	`<div\s[^>]*class="[^"]*` + SignatureWrapperClass + `[^"]*"`)

// signatureIDRe extracts the id from a signature wrapper div, regardless of
// whether id appears before or after the class attribute.
var signatureIDRe = regexp.MustCompile(
	`<div\s[^>]*class="[^"]*` + SignatureWrapperClass + `[^"]*"[^>]*id="([^"]*)"` +
		`|<div\s[^>]*id="([^"]*)"[^>]*class="[^"]*` + SignatureWrapperClass)

func Project(snapshot *DraftSnapshot) DraftProjection {
	proj := DraftProjection{
		Subject:    snapshot.Subject,
		To:         append([]Address{}, snapshot.To...),
		Cc:         append([]Address{}, snapshot.Cc...),
		Bcc:        append([]Address{}, snapshot.Bcc...),
		ReplyTo:    append([]Address{}, snapshot.ReplyTo...),
		InReplyTo:  snapshot.InReplyTo,
		References: snapshot.References,
	}

	if part := findPart(snapshot.Body, snapshot.PrimaryTextPartID); part != nil {
		proj.BodyText = string(part.Body)
	}
	if part := findPart(snapshot.Body, snapshot.PrimaryHTMLPartID); part != nil {
		html := string(part.Body)
		proj.BodyHTMLSummary = summarizeHTML(html)
		proj.HasQuotedContent = hasQuotedContent(html)
		proj.HasSignature = signatureWrapperRe.MatchString(html)
		if proj.HasSignature {
			if m := signatureIDRe.FindStringSubmatch(html); m != nil {
				// alternation regex: id is in m[1] (class-first) or m[2] (id-first)
				if m[1] != "" {
					proj.SignatureID = m[1]
				} else if len(m) >= 3 {
					proj.SignatureID = m[2]
				}
			}
		}
	}

	parts := flattenParts(snapshot.Body)
	inlineCIDs := make(map[string]bool)
	for _, part := range parts {
		if part == nil || part.IsMultipart() {
			continue
		}
		if part.EncodingProblem {
			name := part.FileName()
			if name == "" {
				name = part.PartID
			}
			proj.Warnings = append(proj.Warnings,
				"part "+name+" has encoding problems; its content may be degraded (e.g. malformed base64, bad charset, or unparseable Content-Type)")
		}
		summary := PartSummary{
			PartID:      part.PartID,
			FileName:    part.FileName(),
			ContentType: part.MediaType,
			Disposition: part.ContentDisposition,
			CID:         part.ContentID,
		}
		switch {
		case strings.EqualFold(part.ContentDisposition, "attachment"):
			proj.AttachmentsSummary = append(proj.AttachmentsSummary, summary)
		case strings.EqualFold(part.ContentDisposition, "inline") || part.ContentID != "":
			proj.InlineSummary = append(proj.InlineSummary, summary)
			if part.ContentID != "" {
				inlineCIDs[strings.ToLower(part.ContentID)] = true
			}
		}
	}

	if part := findPart(snapshot.Body, snapshot.PrimaryHTMLPartID); part != nil {
		for _, cid := range extractCIDRefs(string(part.Body)) {
			if !inlineCIDs[strings.ToLower(cid)] {
				proj.Warnings = append(proj.Warnings, "missing inline MIME part for cid:"+cid)
			}
		}
	}

	return proj
}

func flattenParts(root *Part) []*Part {
	if root == nil {
		return nil
	}
	out := []*Part{root}
	for _, child := range root.Children {
		out = append(out, flattenParts(child)...)
	}
	return out
}

func extractCIDRefs(html string) []string {
	matches := cidRefRegexp.FindAllStringSubmatch(html, -1)
	if len(matches) == 0 {
		return nil
	}
	out := make([]string, 0, len(matches))
	seen := make(map[string]bool, len(matches))
	for _, match := range matches {
		cid := strings.Trim(strings.TrimSpace(match[1]), "<>")
		key := strings.ToLower(cid)
		if cid == "" || seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, cid)
	}
	return out
}

// hasQuotedContent reports whether the HTML body contains a reply or
// forward quote block generated by the Lark mail composer.
// Uses regex to match an actual <div> element with the class attribute,
// avoiding false positives from plain-text or code-snippet occurrences.
func hasQuotedContent(html string) bool {
	return quoteWrapperRe.MatchString(html)
}

// SplitAtQuote splits an HTML body into the user-authored content and
// the trailing reply/forward quote block. If no quote block is found,
// quote is empty and body is the original html unchanged.
func SplitAtQuote(html string) (body, quote string) {
	loc := quoteWrapperRe.FindStringIndex(html)
	if loc == nil {
		return html, ""
	}
	return html[:loc[0]], html[loc[0]:]
}

// ── Exported signature HTML utilities ──
// Used by both draft/patch.go (internal) and mail/signature_html.go (cross-package).

// signatureSpacingRe matches 1-2 empty-line divs before the signature.
var signatureSpacingRe = regexp.MustCompile(
	`(?:<div[^>]*><div[^>]*><br></div></div>\s*){1,2}$`)

// SignatureSpacingRe returns the compiled regex for signature spacing detection.
func SignatureSpacingRe() *regexp.Regexp { return signatureSpacingRe }

// SignatureSpacing returns the 2 empty-line divs placed before the signature,
// matching the structure generated by the Lark mail editor.
func SignatureSpacing() string {
	line := `<div style="margin-top:4px;margin-bottom:4px;line-height:1.6"><div dir="auto"><br></div></div>`
	return line + line
}

// BuildSignatureHTML wraps signature content in the standard signature container div.
// sigID is HTML-escaped to prevent attribute injection.
func BuildSignatureHTML(sigID, content string) string {
	return `<div id="` + html.EscapeString(sigID) + `" class="` + SignatureWrapperClass + `" style="padding-top:6px;padding-bottom:6px">` + content + `</div>`
}

// FindMatchingCloseDiv finds the position after the closing </div> that matches
// the <div at startPos, tracking nesting depth.
func FindMatchingCloseDiv(html string, startPos int) int {
	depth := 0
	i := startPos
	for i < len(html) {
		if strings.HasPrefix(html[i:], "<div") {
			depth++
			i += 4
		} else if strings.HasPrefix(html[i:], "</div>") {
			depth--
			i += 6
			if depth == 0 {
				return i
			}
		} else {
			i++
		}
	}
	return len(html)
}

// RemoveSignatureHTML removes the signature block and its preceding spacing from HTML.
// Returns the HTML unchanged if no signature is found.
func RemoveSignatureHTML(html string) string {
	loc := signatureWrapperRe.FindStringIndex(html)
	if loc == nil {
		return html
	}
	sigStart := loc[0]
	sigEnd := FindMatchingCloseDiv(html, sigStart)

	// Extend backward to include preceding spacing.
	beforeSig := html[:sigStart]
	if spacingLoc := signatureSpacingRe.FindStringIndex(beforeSig); spacingLoc != nil {
		sigStart = spacingLoc[0]
	}

	return html[:sigStart] + html[sigEnd:]
}

func summarizeHTML(html string) string {
	trimmed := strings.TrimSpace(html)
	runes := []rune(trimmed)
	if len(runes) <= 240 {
		return trimmed
	}
	return string(runes[:240]) + "..."
}
