// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

package plugin_e2e

import (
	"bytes"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

const shutdownSignalPlugin = `// Code generated by plugin_e2e; DO NOT EDIT.
package plugin

import (
	"context"
	"errors"
	"os"
	"time"

	"github.com/larksuite/cli/extension/platform"
)

func init() {
	platform.Register(
		platform.NewPlugin("shutdown-signal", "0.1.0").
			Wrap("wait", platform.All(), func(platform.Handler) platform.Handler {
				return func(ctx context.Context, _ platform.Invocation) error {
					if err := os.WriteFile(os.Getenv("LARK_CLI_READY_MARKER"), []byte("ready"), 0o600); err != nil {
						return err
					}
					select {
					case <-ctx.Done():
						return ctx.Err()
					case <-time.After(30 * time.Second):
						return errors.New("command context was not canceled")
					}
				}
			}).
			On(platform.Shutdown, "record", func(ctx context.Context, _ *platform.LifecycleContext) error {
				marker := os.Getenv("LARK_CLI_SHUTDOWN_MARKER")
				if marker == "" {
					return errors.New("LARK_CLI_SHUTDOWN_MARKER is empty")
				}
				if err := os.WriteFile(marker, []byte("shutdown"), 0o600); err != nil {
					return err
				}
				if os.Getenv("LARK_CLI_BLOCK_SHUTDOWN") == "1" {
					<-ctx.Done()
					return ctx.Err()
				}
				return nil
			}).
			FailOpen().
			MustBuild())
}
`

func TestSIGINTRunsShutdownHookAndReturns130(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("os.Interrupt cannot be sent to Windows processes")
	}

	fork := startSignalFork(t, false)
	if err := fork.cmd.Process.Signal(os.Interrupt); err != nil {
		t.Fatalf("send SIGINT: %v", err)
	}
	waitErr := waitForForkExit(t, fork, 10*time.Second)

	var exitErr *exec.ExitError
	if !errors.As(waitErr, &exitErr) || exitErr.ExitCode() != 130 {
		t.Fatalf("SIGINT exit error = %v, exit code = %d, want 130; stdout=%s stderr=%s",
			waitErr, fork.cmd.ProcessState.ExitCode(), fork.stdout.String(), fork.stderr.String())
	}
	if data, err := os.ReadFile(fork.shutdownMarker); err != nil || string(data) != "shutdown" {
		t.Fatalf("Shutdown marker = %q, err=%v, want shutdown", data, err)
	}
}

func TestSecondSIGINTForcesExitDuringShutdown(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("os.Interrupt cannot be sent to Windows processes")
	}

	fork := startSignalFork(t, true)
	if err := fork.cmd.Process.Signal(os.Interrupt); err != nil {
		t.Fatalf("send first SIGINT: %v", err)
	}
	waitForMarker(t, fork.shutdownMarker, 10*time.Second)
	if err := fork.cmd.Process.Signal(os.Interrupt); err != nil {
		t.Fatalf("send second SIGINT: %v", err)
	}

	waitErr := waitForForkExit(t, fork, time.Second)
	var exitErr *exec.ExitError
	if !errors.As(waitErr, &exitErr) {
		t.Fatalf("second SIGINT wait error = %v, want signal exit", waitErr)
	}
	if exitErr.ExitCode() != -1 || !strings.Contains(waitErr.Error(), "interrupt") {
		t.Fatalf("second SIGINT exit = %v, want interrupt signal termination; stderr=%s", waitErr, fork.stderr.String())
	}
}

type signalFork struct {
	cmd            *exec.Cmd
	stdout         bytes.Buffer
	stderr         bytes.Buffer
	shutdownMarker string
}

func startSignalFork(t *testing.T, blockShutdown bool) *signalFork {
	t.Helper()
	bin := buildFork(t, "shutdown-signal", shutdownSignalPlugin)
	markerDir := t.TempDir()
	readyMarker := filepath.Join(markerDir, "ready")
	fork := &signalFork{
		cmd:            exec.Command(bin, "schema"),
		shutdownMarker: filepath.Join(markerDir, "shutdown"),
	}
	fork.cmd.Env = append(isolatedEnv(t),
		"LARK_CLI_READY_MARKER="+readyMarker,
		"LARK_CLI_SHUTDOWN_MARKER="+fork.shutdownMarker,
	)
	if blockShutdown {
		fork.cmd.Env = append(fork.cmd.Env, "LARK_CLI_BLOCK_SHUTDOWN=1")
	}
	fork.cmd.Stdout = &fork.stdout
	fork.cmd.Stderr = &fork.stderr
	if err := fork.cmd.Start(); err != nil {
		t.Fatalf("start fork: %v", err)
	}
	t.Cleanup(func() {
		if fork.cmd.ProcessState == nil {
			_ = fork.cmd.Process.Kill()
			_ = fork.cmd.Wait()
		}
	})
	waitForMarker(t, readyMarker, 10*time.Second)
	return fork
}

func waitForForkExit(t *testing.T, fork *signalFork, timeout time.Duration) error {
	t.Helper()
	waitCh := make(chan error, 1)
	go func() { waitCh <- fork.cmd.Wait() }()
	select {
	case err := <-waitCh:
		return err
	case <-time.After(timeout):
		_ = fork.cmd.Process.Kill()
		t.Fatalf("fork did not exit within %s; stdout=%s stderr=%s", timeout, fork.stdout.String(), fork.stderr.String())
		return nil
	}
}

func waitForMarker(t *testing.T, path string, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if _, err := os.Stat(path); err == nil {
			return
		}
		time.Sleep(10 * time.Millisecond)
	}
	t.Fatalf("marker %s was not created within %s", path, timeout)
}
